server {
    listen 80;
    server_name driver-tracker.local;

    location /user-api/ {
        proxy_pass http://host.docker.internal:8081/;
        proxy_set_header Host $host;
    }

    location /location-api/ {
        proxy_pass http://host.docker.internal:8084/;
        proxy_set_header Host $host;
    }

    location /order-api/ {
        proxy_pass http://host.docker.internal:8082/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://driverid-app:5173/;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}